name: Example Dependency Submission
on:
  push
#on:
  #push:
    #branches:
      #- main
jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Run dependency submission
        uses: ./
        id: example
        with:
          npm-package-directory: ./
